from .._wrapper import *

GL_OVR_multiview = 1
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_NUM_VIEWS_OVR = 0x9630
GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_BASE_VIEW_INDEX_OVR = 0x9632
GL_MAX_VIEWS_OVR = 0x9631
GL_FRAMEBUFFER_INCOMPLETE_VIEW_TARGETS_OVR = 0x9633
PFNGLFRAMEBUFFERTEXTUREMULTIVIEWOVRPROC = C(
    None, UInt, UInt, UInt, Int, Int, Int
)
glFramebufferTextureMultiviewOVR = GL(
    'glFramebufferTextureMultiviewOVR', None, UInt, UInt, UInt, Int, Int, Int
)
GL_OVR_multiview2 = 1

__all__ = [
    'GL_OVR_multiview', 'GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_NUM_VIEWS_OVR',
    'GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_BASE_VIEW_INDEX_OVR',
    'GL_MAX_VIEWS_OVR', 'GL_FRAMEBUFFER_INCOMPLETE_VIEW_TARGETS_OVR',
    'PFNGLFRAMEBUFFERTEXTUREMULTIVIEWOVRPROC',
    'glFramebufferTextureMultiviewOVR', 'GL_OVR_multiview2'
]
