from .._wrapper import *

GL_INTEL_blackhole_render = 1
GL_BLACKHOLE_RENDER_INTEL = 0x83FC
GL_INTEL_conservative_rasterization = 1
GL_CONSERVATIVE_RASTERIZATION_INTEL = 0x83FE
GL_INTEL_framebuffer_CMAA = 1
PFNGLAPPLYFRAMEBUFFERATTACHMENTCMAAINTELPROC = C(None)
glApplyFramebufferAttachmentCMAAINTEL = GL(
    'glApplyFramebufferAttachmentCMAAINTEL', None
)
GL_INTEL_performance_query = 1
GL_PERFQUERY_SINGLE_CONTEXT_INTEL = 0x00000000
GL_PERFQUERY_GLOBAL_CONTEXT_INTEL = 0x00000001
GL_PERFQUERY_WAIT_INTEL = 0x83FB
GL_PERFQUERY_FLUSH_INTEL = 0x83FA
GL_PERFQUERY_DONOT_FLUSH_INTEL = 0x83F9
GL_PERFQUERY_COUNTER_EVENT_INTEL = 0x94F0
GL_PERFQUERY_COUNTER_DURATION_NORM_INTEL = 0x94F1
GL_PERFQUERY_COUNTER_DURATION_RAW_INTEL = 0x94F2
GL_PERFQUERY_COUNTER_THROUGHPUT_INTEL = 0x94F3
GL_PERFQUERY_COUNTER_RAW_INTEL = 0x94F4
GL_PERFQUERY_COUNTER_TIMESTAMP_INTEL = 0x94F5
GL_PERFQUERY_COUNTER_DATA_UINT32_INTEL = 0x94F8
GL_PERFQUERY_COUNTER_DATA_UINT64_INTEL = 0x94F9
GL_PERFQUERY_COUNTER_DATA_FLOAT_INTEL = 0x94FA
GL_PERFQUERY_COUNTER_DATA_DOUBLE_INTEL = 0x94FB
GL_PERFQUERY_COUNTER_DATA_BOOL32_INTEL = 0x94FC
GL_PERFQUERY_QUERY_NAME_LENGTH_MAX_INTEL = 0x94FD
GL_PERFQUERY_COUNTER_NAME_LENGTH_MAX_INTEL = 0x94FE
GL_PERFQUERY_COUNTER_DESC_LENGTH_MAX_INTEL = 0x94FF
GL_PERFQUERY_GPA_EXTENDED_COUNTERS_INTEL = 0x9500
PFNGLBEGINPERFQUERYINTELPROC = C(None, UInt)
PFNGLCREATEPERFQUERYINTELPROC = C(None, UInt, P(UInt))
PFNGLDELETEPERFQUERYINTELPROC = C(None, UInt)
PFNGLENDPERFQUERYINTELPROC = C(None, UInt)
PFNGLGETFIRSTPERFQUERYIDINTELPROC = C(None, P(UInt))
PFNGLGETNEXTPERFQUERYIDINTELPROC = C(None, UInt, P(UInt))
PFNGLGETPERFCOUNTERINFOINTELPROC = C(
    None, UInt, UInt, UInt, CharP, UInt, CharP, P(UInt), P(UInt), P(UInt),
    P(UInt), P(ULong)
)
PFNGLGETPERFQUERYDATAINTELPROC = C(None, UInt, UInt, Int, VoidP, P(UInt))
PFNGLGETPERFQUERYIDBYNAMEINTELPROC = C(None, CharP, P(UInt))
PFNGLGETPERFQUERYINFOINTELPROC = C(
    None, UInt, UInt, CharP, P(UInt), P(UInt), P(UInt), P(UInt)
)
glBeginPerfQueryINTEL = GL('glBeginPerfQueryINTEL', None, UInt)
glCreatePerfQueryINTEL = GL('glCreatePerfQueryINTEL', None, UInt, P(UInt))
glDeletePerfQueryINTEL = GL('glDeletePerfQueryINTEL', None, UInt)
glEndPerfQueryINTEL = GL('glEndPerfQueryINTEL', None, UInt)
glGetFirstPerfQueryIdINTEL = GL('glGetFirstPerfQueryIdINTEL', None, P(UInt))
glGetNextPerfQueryIdINTEL = GL(
    'glGetNextPerfQueryIdINTEL', None, UInt, P(UInt)
)
glGetPerfCounterInfoINTEL = GL(
    'glGetPerfCounterInfoINTEL', None, UInt, UInt, UInt, CharP, UInt, CharP,
    P(UInt), P(UInt), P(UInt), P(UInt), P(ULong)
)
glGetPerfQueryDataINTEL = GL(
    'glGetPerfQueryDataINTEL', None, UInt, UInt, Int, VoidP, P(UInt)
)
glGetPerfQueryIdByNameINTEL = GL(
    'glGetPerfQueryIdByNameINTEL', None, CharP, P(UInt)
)
glGetPerfQueryInfoINTEL = GL(
    'glGetPerfQueryInfoINTEL', None, UInt, UInt, CharP, P(UInt), P(UInt),
    P(UInt), P(UInt)
)

__all__ = [
    'GL_INTEL_blackhole_render', 'GL_BLACKHOLE_RENDER_INTEL',
    'GL_INTEL_conservative_rasterization',
    'GL_CONSERVATIVE_RASTERIZATION_INTEL', 'GL_INTEL_framebuffer_CMAA',
    'PFNGLAPPLYFRAMEBUFFERATTACHMENTCMAAINTELPROC',
    'glApplyFramebufferAttachmentCMAAINTEL', 'GL_INTEL_performance_query',
    'GL_PERFQUERY_SINGLE_CONTEXT_INTEL', 'GL_PERFQUERY_GLOBAL_CONTEXT_INTEL',
    'GL_PERFQUERY_WAIT_INTEL', 'GL_PERFQUERY_FLUSH_INTEL',
    'GL_PERFQUERY_DONOT_FLUSH_INTEL', 'GL_PERFQUERY_COUNTER_EVENT_INTEL',
    'GL_PERFQUERY_COUNTER_DURATION_NORM_INTEL',
    'GL_PERFQUERY_COUNTER_DURATION_RAW_INTEL',
    'GL_PERFQUERY_COUNTER_THROUGHPUT_INTEL', 'GL_PERFQUERY_COUNTER_RAW_INTEL',
    'GL_PERFQUERY_COUNTER_TIMESTAMP_INTEL',
    'GL_PERFQUERY_COUNTER_DATA_UINT32_INTEL',
    'GL_PERFQUERY_COUNTER_DATA_UINT64_INTEL',
    'GL_PERFQUERY_COUNTER_DATA_FLOAT_INTEL',
    'GL_PERFQUERY_COUNTER_DATA_DOUBLE_INTEL',
    'GL_PERFQUERY_COUNTER_DATA_BOOL32_INTEL',
    'GL_PERFQUERY_QUERY_NAME_LENGTH_MAX_INTEL',
    'GL_PERFQUERY_COUNTER_NAME_LENGTH_MAX_INTEL',
    'GL_PERFQUERY_COUNTER_DESC_LENGTH_MAX_INTEL',
    'GL_PERFQUERY_GPA_EXTENDED_COUNTERS_INTEL',
    'PFNGLBEGINPERFQUERYINTELPROC', 'PFNGLCREATEPERFQUERYINTELPROC',
    'PFNGLDELETEPERFQUERYINTELPROC', 'PFNGLENDPERFQUERYINTELPROC',
    'PFNGLGETFIRSTPERFQUERYIDINTELPROC', 'PFNGLGETNEXTPERFQUERYIDINTELPROC',
    'PFNGLGETPERFCOUNTERINFOINTELPROC', 'PFNGLGETPERFQUERYDATAINTELPROC',
    'PFNGLGETPERFQUERYIDBYNAMEINTELPROC', 'PFNGLGETPERFQUERYINFOINTELPROC',
    'glBeginPerfQueryINTEL', 'glCreatePerfQueryINTEL',
    'glDeletePerfQueryINTEL', 'glEndPerfQueryINTEL',
    'glGetFirstPerfQueryIdINTEL', 'glGetNextPerfQueryIdINTEL',
    'glGetPerfCounterInfoINTEL', 'glGetPerfQueryDataINTEL',
    'glGetPerfQueryIdByNameINTEL', 'glGetPerfQueryInfoINTEL'
]
